framework:
    messenger:
        failure_transport: failed

<<<<<<< Updated upstream
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
=======
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: "doctrine://default?queue_name=failed"
      sync: "sync://"
>>>>>>> Stashed changes

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

<<<<<<< Updated upstream
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
=======
    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: mailer
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async
>>>>>>> Stashed changes

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
